# Generated by Django 6.0.2 on 2026-04-18 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuKiemTra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_khoa', models.CharField(max_length=255)),
                ('tu_khoa_goc', models.CharField(blank=True, max_length=255)),
                ('diem_rui_ro', models.PositiveSmallIntegerField(default=0)),
                ('muc_rui_ro', models.CharField(default='Thấp', max_length=20)),
                ('co_rui_ro', models.BooleanField(default=False)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_kiem_tra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
